const referenceNode = document.querySelector('body > div.mkdf-wrapper > div.mkdf-wrapper-inner > div.mkdf-content > div > div > div > div > div > div:nth-child(5)');
const newNode = document.createElement('div');
newNode.classList.add('mkdf-row-grid-section-wrapper');
newNode.innerHTML = '<div class="mkdf-row-grid-section"> <style>#honda-widget-link-literal1{font-size: 3.5vw; margin-bottom: 1.7vw; line-height: 1.2;}#honda-widget-link-literal2{font-size: 3vw; margin-bottom: 1.7vw; line-height: 1.2;}#honda-widget-link-literal3{font-size: 2.5vw; line-height: 1.2;}#honda-logo{height: 2.5vw;}#cta-effect{border-color: #ff1e1c !important;}#cta-effect.active{border-color: transparent !important; transform: scale(1.5); transition: all 1s;}@media (min-width: 1300px){#honda-widget-link-literal1{font-size: 40px; margin-bottom: 22px;}#honda-widget-link-literal2{font-size: 36px; margin-bottom: 22px;}#honda-widget-link-literal3{font-size: 24px;}#honda-logo{height: 26px;}}</style> <a href="/honda-civic" id="honda-widget-link" class="honda-widget" style="display: flex; justify-content: right; background-image: url(\'https://ik.imagekit.io/6awugugrs/honda/widget-bg.jpg\'); background-size: cover; aspect-ratio: 1300 / 300; padding: 0 .5rem;"> <div style="flex: 0 0 auto; width: auto; display: flex; align-items: center; padding: 0 .5rem;"> <div style="text-align: center;"> <span id="honda-widget-link-literal1" style="display: block; color: #ff1e1c; font-weight: 700;">HONDA CIVIC e:HEV</span> <span id="honda-widget-link-literal2" style="display: block; color: white; font-weight: 100;">Το ταξίδι ξεκινά!</span> <div id="honda-widget-link-literal3" style="color: white;"> <span>Sponsored by </span> <img src="https://ik.imagekit.io/6awugugrs/honda/logo.png" id="honda-logo" alt="Honda"> </div></div></div><div style="flex: 0 0 auto; width: auto; display: flex; align-items: center; justify-content: center; padding: 0 .5rem;"> <div style="width: 45px; height: 45px; position: relative;"> <div id="cta-effect" style="border-radius: 50%; border: 1px solid; width: 43px; height: 43px; position: absolute; top: 0;"></div><div style="border-radius: 50%; background-color: #ff1e1c; display: flex; align-items: center; justify-content: center; position: absolute; top: 0; width: 45px; height: 45px;"> <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-arrow-right" viewBox="0 0 16 16"> <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/> </svg> </div></div></div></a> </div>';
referenceNode.parentNode.insertBefore(newNode, referenceNode.nextSibling);
const ctaEffect = document.getElementById('cta-effect');
setInterval(function() {
    ctaEffect.classList.remove('active');
    ctaEffect.classList.add('active');
}, 1000);